-- MySQL Script generated by MySQL Workbench
-- 10/30/16 15:08:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Recorrido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Recorrido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Recorrido` (
  `codigoRecorrido` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`codigoRecorrido`),
  UNIQUE INDEX `codigoRecorrido_UNIQUE` (`codigoRecorrido` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Micro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Micro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Micro` (
  `idMicro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(12) NOT NULL,
  `longitud` DECIMAL(30,26) NOT NULL,
  `latitud` DECIMAL(30,26) NOT NULL,
  `Recorrido_codigoRecorrido` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idMicro`),
  UNIQUE INDEX `idMicro_UNIQUE` (`idMicro` ASC),
  INDEX `fk_Micro_Recorrido1_idx` (`Recorrido_codigoRecorrido` ASC),
  CONSTRAINT `fk_Micro_Recorrido1`
    FOREIGN KEY (`Recorrido_codigoRecorrido`)
    REFERENCES `mydb`.`Recorrido` (`codigoRecorrido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paradero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Paradero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Paradero` (
  `idParadero` INT NOT NULL AUTO_INCREMENT,
  `latitud` DECIMAL(30,26) NOT NULL,
  `longitud` DECIMAL(30,26) NOT NULL,
  PRIMARY KEY (`idParadero`),
  UNIQUE INDEX `idParadero_UNIQUE` (`idParadero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `rutCliente` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `contraseña` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`rutCliente`),
  UNIQUE INDEX `rutCliente_UNIQUE` (`rutCliente` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParaderoDeRecorrido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ParaderoDeRecorrido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ParaderoDeRecorrido` (
  `Recorrido_codigoRecorrido` VARCHAR(5) NOT NULL,
  `Paradero_idParadero` INT NOT NULL,
  INDEX `fk_ParaderoDeRecorrido_Recorrido1_idx` (`Recorrido_codigoRecorrido` ASC),
  INDEX `fk_ParaderoDeRecorrido_Paradero1_idx` (`Paradero_idParadero` ASC),
  CONSTRAINT `fk_ParaderoDeRecorrido_Recorrido1`
    FOREIGN KEY (`Recorrido_codigoRecorrido`)
    REFERENCES `mydb`.`Recorrido` (`codigoRecorrido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ParaderoDeRecorrido_Paradero1`
    FOREIGN KEY (`Paradero_idParadero`)
    REFERENCES `mydb`.`Paradero` (`idParadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
